version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db@12345
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent storage for DB data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Initialization script

volumes:
  postgres-data:
